### ISSUE TITLE
Getting `Node 12 actions are deprecated` when running workflow

### ISSUE THREAD

**Issue by vfernandestoptal** [browserstack/github-actions#19]
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16:  browserstack/github-actions
```

Are you planning to update this action to use Node 16?

**Comment by xavierfoucrier** [comment]
@rchougule @sourav-kundu any updates about this?
This is still a **serious issue** for everyone using the Github Action.

Thanks for adding this to the roadmap and merging soon! 😎

**Comment by cgdibble** [comment]
We'd also love an update on this as well. Are there plans for getting https://github.com/browserstack/github-actions/pull/21 merged?
