### ISSUE TITLE
Getting a suffix added to BROWSERSTACK_USERNAME `-GitHubAction`

### ISSUE THREAD

**Issue by SachaTe** [browserstack/github-actions#20]
I noticed when using this plugin that for some reason when I later on reference `BROWSERSTACK_USERNAME` there is an added suffix of `-GitHubAction`, this does not appear with other environment variables like access key.

**Comment by rahulHbrowserstack** [comment]
I request you to please share the screenshot where you are experiencing the same behaviour.

**Comment by francisf** [comment]
@SachaTe  this is something that helps BrowserStack identify which CI was used to run tests. This does not impact test  execution in any way.

**Comment by SachaTe** [comment]
But with this suffix, if we specify the username it gives an error

**Comment by francisf** [comment]
Could you please share details around the error and the steps you performed. You can  email  support@browserstack.com or fill the info in [the contact page](https://www.browserstack.com/contact#technical-support)

**Comment by SachaTe** [comment]
There is no error, it would just be very convenient and practical to allow the build ID to be accessed somehow without having to parse the console dumb
