### ISSUE TITLE
Some commands are deprecated and will be disabled soon

### ISSUE THREAD

**Issue by xavierfoucrier** [browserstack/github-actions#6]
Hi Browserstack team,

I got **some warnings** when running the Github Actions:

> Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

> Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Thanks for the fix! :wink:

**Comment by Archish27** [comment]
Thanks! 👍  @xavierfoucrier
